### ISSUE TITLE
phpunit will fail in testing stage, if database testing presence in tests

### ISSUE THREAD

**Issue by SadeghPM** [ohdearapp/gitlab-ci-pipeline-for-laravel#3]
Hi.
If we have database tests in testing stage, phpunit test will be fail. Because no database seeding in this test.
How ohdearapp pass phpunit? Adding `php artisan migrate:fresh --seed` script could be solve this issue.
thanks

**Comment by mattiasgeniar** [comment]
Hi @SadeghPM !

This should still work if you use our example to start from, the database seeding happens before the `testing` stage.

Are you getting an error message? If so, could you share it?

Thx,

M.

**Comment by SadeghPM** [comment]
In phpunit test i get database errors and every database relation test will be fail due to missing migration and seeding:
all errors is  `Base table or view not found`.
```
.
.
.
$ php -d short_open_tag=off ./vendor/phpunit/phpunit/phpunit -v --colors=never --stderr
PHPUnit 7.5.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.14
Configuration: /builds/SadeghPM/digikop/phpunit.xml

.FEEEFFE                                                            8 / 8 (100%)

Time: 403 ms, Memory: 28.00MB

There were 4 errors:

1) Tests\Feature\AdSearchPageTest::testCityWillBeInSession
Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'digikop_db.cities' doesn't exist (SQL: select * from `cities` order by RAND() limit 1)
```
![pipeline](https://user-images.githubusercontent.com/9298600/51316721-beb68900-1a6a-11e9-84a6-151dac8567d0.png)

If migration script presence before phpunit script, then test will be passed!
My .gitlab-ci.yaml file:
```yaml
stages:
  - preparation
  - building
  - testing
  - security

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: digikop_user
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: digikop_db
  DB_HOST: mysql

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

composer:
  stage: preparation
  services:
    - mysql:5.7
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  script:
    - php -v
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
  artifacts:
    paths:
      - vendor/
      - .env
    expire_in: 1 days
    when: always
  cache:
    paths:
      - vendor/

yarn:
  stage: preparation
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  script:
    - yarn --version
    - yarn install --pure-lockfile
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 days
    when: always
  cache:
    paths:
      - node_modules/

build-assets:
  stage: building
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  # Download the artifacts for these jobs
  dependencies:
    - composer
    - yarn
  script:
    - yarn --version
    - yarn run production --progress false
  artifacts:
    paths:
      - public/css/
      - public/js/
      - public/fonts/
      - public/mix-manifest.json
    expire_in: 1 days
    when: always

db-seeding:
  stage: building
  services:
    - mysql:5.7
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  # Download the artifacts for these jobs
  dependencies:
    - composer
    - yarn
  script:
    - php artisan migrate:fresh --seed
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: on_failure

phpunit:
  stage: testing
  services:
    - mysql:5.7
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  # Download the artifacts for these jobs
  dependencies:
    - build-assets
    - composer
    - db-seeding
  script:
    - php -v
    - sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak
    - echo "" | sudo tee /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - ./vendor/phpunit/phpunit/phpunit --version
    - php -d short_open_tag=off ./vendor/phpunit/phpunit/phpunit -v --colors=never --stderr
    - sudo cp /usr/local/etc/php/conf.d/docker-php-ext-xdebug.bak /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: on_failure

codestyle:
  stage: testing
  image: lorisleiva/laravel-docker
  script:
    - phpcs
  dependencies: []

phpcpd:
  stage: testing
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  script:
    - test -f phpcpd.phar || curl -L https://phar.phpunit.de/phpcpd.phar -o phpcpd.phar
    - php phpcpd.phar
  dependencies: []
  cache:
    paths:
      - phpcpd.phar

sensiolabs:
  stage: security
  image: edbizarro/gitlab-ci-pipeline-php:7.2
  script:
    - test -d security-checker || git clone https://github.com/sensiolabs/security-checker.git
    - cd security-checker
    - composer install
    - php security-checker security:check ../composer.lock
  dependencies: []
  cache:
    paths:
      - security-checker/

```
